services:
  - type: web
    name: hardcoded-api-key-detector
    env: static
    buildCommand: cd landing && npm install && npm run build
    staticPublishPath: ./landing/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
